# Use root/example as user/password credentials
# https://trainto.me/docker-mongodb-replicaset/
version: '3.7'

services:
  mongo-member1:
    container_name: mongo-member1
    image: mongo:latest
    volumes: 
      - $HOME/data/rs1:/data/db
    ports: 
      - 27017:27017
    restart: always
    command: --replSet mdbDefGuide --oplogSize 200
  mongo-member2:
    container_name: mongo-member2
    image: mongo:latest
    volumes: 
      - $HOME/data/rs2:/data/db
    ports: 
      - 27018:27017
    restart: always
    command: --replSet mdbDefGuide --oplogSize 200
  mongo-member3:
    container_name: mongo-member3
    image: mongo:latest
    volumes: 
      - $HOME/data/rs3:/data/db
    ports: 
      - 27019:27017
    restart: always
    command: --replSet mdbDefGuide --oplogSize 200
  mongo-member4:
    container_name: mongo-member4
    image: mongo:latest
    volumes: 
      - $HOME/data/rs4:/data/db
    ports: 
      - 27020:27017
    restart: always
    command: --replSet mdbDefGuide --oplogSize 200
    