# Use root/example as user/password credentials
# https://trainto.me/docker-mongodb-replicaset/
version: '3.7'

services:
  mongo-primary:
    container_name: mongo-primary
    image: mongo:latest
    volumes: 
      - $HOME/data/rs1:/data/db
    ports: 
      - 27017:27017
    restart: always
    command: --replSet mdbDefGuide --oplogSize 200
  mongo-secondary:
    container_name: mongo-secondary
    image: mongo:latest
    volumes: 
      - $HOME/data/rs2:/data/db
    ports: 
      - 27018:27017
    restart: always
    command: --replSet mdbDefGuide --oplogSize 200
  mongo-secondary2:
    container_name: mongo-secondary2
    image: mongo:latest
    volumes: 
      - $HOME/data/rs3:/data/db
    ports: 
      - 27019:27017
    restart: always
    command: --replSet mdbDefGuide --oplogSize 200
    